# .github/workflows/docker-build.yml
name: Build and Push to ECR on Main Merge

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2        # 예: 서울 리전
  ECR_NAMESPACE: rehasher-team
  ECR_REPOSITORY: rehash-backend     # ECR 리포지토리 이름
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region = $AWS_REGION" >> ~/.aws/config

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-northeast-2 | \
            docker login --username AWS --password-stdin 215626476886.dkr.ecr.ap-northeast-2.amazonaws.com

      - name: Build, tag, and push Docker image
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
          IMAGE_URI="215626476886.dkr.ecr.ap-northeast-2.amazonaws.com/$ECR_NAMESPACE/$ECR_REPOSITORY:$IMAGE_TAG"

          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
